# Generated by Django 2.2 on 2019-04-07 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbidb_app', '0002_auto_20190407_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quick_message', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('email_sent', models.BooleanField()),
                ('not_interested', models.BooleanField()),
                ('requires_clarification', models.BooleanField()),
                ('quotation_received', models.DateField(blank=True, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbidb_app.Contact')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbidb_app.Project')),
            ],
        ),
        migrations.DeleteModel(
            name='ProjectList',
        ),
    ]
