# Generated by Django 2.2 on 2019-04-07 23:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbidb_app', '0003_auto_20190407_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date_used',
            field=models.DateField(default=datetime.date(2019, 4, 8)),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='projectcontact',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='projectcontact',
            name='not_interested',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='projectcontact',
            name='requires_clarification',
            field=models.BooleanField(default=False),
        ),
    ]
