# Generated by Django 2.2 on 2019-04-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbidb_app', '0005_auto_20190414_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_logo',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
