# Generated by Django 2.2 on 2019-04-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbidb_app', '0007_auto_20190420_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='email_notes',
            new_name='email_note3',
        ),
        migrations.AddField(
            model_name='project',
            name='email_description1',
            field=models.TextField(blank=True, default='Please see the short description of the project below:', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='email_general_notes',
            field=models.TextField(blank=True, default='Note1\nNote2\nNote3', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='email_greetng',
            field=models.TextField(blank=True, default='Hello', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='email_invitation1',
            field=models.TextField(blank=True, default='We are currently preparing a tender for the project:', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='email_invitation2',
            field=models.TextField(blank=True, default=' and we would like to invite you to submit your most competitive  quotation for', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='email_note1',
            field=models.TextField(blank=True, default='Please note the following:', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='email_note2',
            field=models.TextField(blank=True, default='We require your final quotation before end of ', null=True),
        ),
    ]
