# Generated by Django 2.2 on 2019-04-20 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbidb_app', '0008_auto_20190420_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='quotations_deadline',
            new_name='email_quotations_deadline',
        ),
    ]
