# Generated by Django 2.2 on 2019-04-20 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbidb_app', '0009_auto_20190420_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='email_greetng',
            new_name='email_greeting',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='email_quotations_deadline',
            new_name='email_quotation_deadline',
        ),
    ]
