# Generated by Django 2.2 on 2019-04-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbidb_app', '0010_auto_20190420_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='email_greeting',
            field=models.CharField(blank=True, default='Hello', max_length=50, null=True),
        ),
    ]
