# Generated by Django 2.2 on 2019-04-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbidb_app', '0012_auto_20190420_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='email_attachment_full',
            field=models.TextField(blank=True, default='-- PASTE LINK FOR FULL TENDER DOCS LINK HERE --', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='email_general_notes',
            field=models.TextField(blank=True, default='Your tender must be fixed price and remain open for acceptance for a period of six months from the date of return or 14 days greater than the validity period stated in the Main Contract, whichever is the longer.\nThe sub-contractor is responsible for obtaining all further information (and will be deemed to have done so) in order to ensure the sufficiency of your tender.\nThe information made available in connection with this invitation to tender is confidential and must not be divulged beyond the degree necessary to prepare your tender.\nWorks must be carried out in accordance with Balfour Beatty Subcontractors Health, Safety, Environment, Quality and Sustainability Conditions.\n\nIf you require any further information please do not hesitate to contact me.', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='email_note2',
            field=models.TextField(blank=True, default='Please submit your tenders no later than 5pm on', null=True),
        ),
    ]
