# Generated by Django 2.2 on 2019-04-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbidb_app', '0013_auto_20190420_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='email_attachment_full',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectcontact',
            name='email_attachment_category_specific',
            field=models.TextField(blank=True, null=True),
        ),
    ]
