# Generated by Django 2.2 on 2019-04-22 15:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bbidb_app', '0016_contact_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='archivised',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='archivised',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='archivised',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectcontact',
            name='archivised',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectcontact',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='company',
            name='date_added',
            field=models.DateField(blank=True, default=datetime.date(2019, 4, 22), null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date_used',
            field=models.DateField(default=datetime.date(2019, 4, 22)),
        ),
    ]
