# Generated by Django 2.2 on 2019-04-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbidb_app', '0018_auto_20190422_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='archivised',
            field=models.BooleanField(default=False),
        ),
    ]
