# Generated by Django 2.2 on 2019-04-23 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbidb_app', '0020_auto_20190423_0848'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='category',
            order_with_respect_to='name',
        ),
    ]
