# Generated by Django 2.2 on 2019-04-23 11:47

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bbidb_app', '0025_auto_20190423_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='date_added',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 4, 23, 11, 47, 16, 603390, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='bbidb_app.Category'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date_used',
            field=models.DateField(default=datetime.datetime(2019, 4, 23, 11, 47, 16, 619015, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='ProjectContactWorks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_message', models.TextField(blank=True, null=True)),
                ('email_category_attachment', models.TextField(blank=True, null=True)),
                ('archivised', models.BooleanField(default=False)),
                ('category', models.ManyToManyField(blank=True, null=True, to='bbidb_app.Category')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bbidb_app.Project')),
            ],
        ),
        migrations.AddField(
            model_name='projectcontact',
            name='works',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bbidb_app.ProjectContactWorks'),
        ),
    ]
