# Generated by Django 2.2 on 2019-04-24 08:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bbidb_app', '0029_auto_20190423_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='archivised_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='archivised_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='date_updated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='date_added',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='date_updated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='archivised_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='date_added',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='date_updated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectcontact',
            name='archivised_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectcontact',
            name='date_added',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectcontact',
            name='date_updated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectcontactworks',
            name='archivised_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='date_added',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 4, 24, 8, 28, 36, 967172, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date_used',
            field=models.DateField(default=datetime.datetime(2019, 4, 24, 8, 28, 36, 967172, tzinfo=utc)),
        ),
    ]
