# Generated by Django 2.2 on 2019-04-25 09:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bbidb_app', '0036_auto_20190425_0954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectcontactworks',
            options={'verbose_name_plural': 'project contact works'},
        ),
        migrations.AlterField(
            model_name='company',
            name='date_added',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 4, 25, 9, 46, 31, 50845, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date_added',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 4, 25, 9, 46, 31, 50845, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date_used',
            field=models.DateField(default=datetime.datetime(2019, 4, 25, 9, 46, 31, 50845, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_added',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 4, 25, 9, 46, 31, 50845, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='projectcontact',
            name='archivised_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectcontact',
            name='quotation_received',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
