# Generated by Django 2.2 on 2019-04-25 11:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bbidb_app', '0037_auto_20190425_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectcontact',
            name='email_sent',
        ),
        migrations.RemoveField(
            model_name='projectcontact',
            name='not_interested',
        ),
        migrations.RemoveField(
            model_name='projectcontact',
            name='requires_clarification',
        ),
        migrations.AddField(
            model_name='projectcontact',
            name='email_sent_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectcontact',
            name='not_interested_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectcontact',
            name='requires_clarification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='date_added',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 4, 25, 11, 54, 39, 586789, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date_added',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 4, 25, 11, 54, 39, 586789, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date_used',
            field=models.DateField(default=datetime.datetime(2019, 4, 25, 11, 54, 39, 586789, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_added',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 4, 25, 11, 54, 39, 602443, tzinfo=utc), null=True),
        ),
    ]
