# Generated by Django 2.2 on 2019-04-25 15:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bbidb_app', '0040_auto_20190425_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='email_cc',
            field=models.TextField(blank=True, default='paul.bolger@balfourbeatty.com; matthew.fudala@balfourbeatty.com', null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='date_added',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 4, 25, 15, 52, 42, 123027, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date_added',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 4, 25, 15, 52, 42, 127015, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date_used',
            field=models.DateField(default=datetime.datetime(2019, 4, 25, 15, 52, 42, 127015, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_added',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 4, 25, 15, 52, 42, 130010, tzinfo=utc), null=True),
        ),
    ]
