# Generated by Django 2.2 on 2019-04-25 16:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bbidb_app', '0042_auto_20190425_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='date_added',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 4, 25, 16, 32, 30, 902178, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date_added',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 4, 25, 16, 32, 30, 903172, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date_used',
            field=models.DateField(default=datetime.datetime(2019, 4, 25, 16, 32, 30, 903172, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_added',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 4, 25, 16, 32, 30, 906165, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='email_general_notes',
            field=models.TextField(blank=True, default='Your tender must be fixed price and remain open for acceptance for a period of six months from the date of return or 14 days greater than the validity period stated in the Main Contract, whichever is the longer.\nThe sub-contractor is responsible for obtaining all further information (and will be deemed to have done so) in order to ensure the sufficiency of your tender.\nThe information made available in connection with this invitation to tender is confidential and must not be divulged beyond the degree necessary to prepare your tender.\nWorks must be carried out in accordance with Balfour Beatty Subcontractors Health, Safety, Environment, Quality and Sustainability Conditions.', null=True),
        ),
    ]
