# Generated by Django 2.2 on 2019-05-08 10:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bbidb_app', '0053_auto_20190508_1044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={},
        ),
        migrations.AlterField(
            model_name='company',
            name='date_added',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 5, 8, 10, 7, 59, 251379, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date_added',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 5, 8, 10, 7, 59, 251379, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date_used',
            field=models.DateField(default=datetime.datetime(2019, 5, 8, 10, 7, 59, 251379, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_added',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 5, 8, 10, 7, 59, 266999, tzinfo=utc), null=True),
        ),
        migrations.AlterOrderWithRespectTo(
            name='contact',
            order_with_respect_to='category',
        ),
    ]
