# Generated by Django 2.2 on 2019-05-08 15:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bbidb_app', '0055_auto_20190508_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='date_added',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 5, 8, 15, 54, 55, 516031, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date_added',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 5, 8, 15, 54, 55, 516031, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date_used',
            field=models.DateField(default=datetime.datetime(2019, 5, 8, 15, 54, 55, 516031, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_added',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 5, 8, 15, 54, 55, 531686, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='email_general_notes',
            field=models.TextField(blank=True, default='- Your tender must be fixed price and remain open for acceptance for a period of six months from the date of return or 14 days greater than the validity period stated in the Main Contract, whichever is the longer.\n- The sub-contractor is responsible for obtaining all further information (and will be deemed to have done so) in order to ensure the sufficiency of your tender.\n- The information made available in connection with this invitation to tender is confidential and must not be divulged beyond the degree necessary to prepare your tender.\n- Works must be carried out in accordance with Balfour Beatty Subcontractors Health, Safety, Environment, Quality and Sustainability Conditions.', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='email_note2',
            field=models.TextField(blank=True, default='- Please submit your tenders no later than 5pm on', null=True),
        ),
    ]
