# Generated by Django 2.2 on 2019-05-19 13:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bbidb_app', '0056_auto_20190508_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='boq',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='company',
            name='date_added',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 5, 19, 13, 6, 8, 799171, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date_added',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 5, 19, 13, 6, 8, 803699, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date_used',
            field=models.DateField(default=datetime.datetime(2019, 5, 19, 13, 6, 8, 803699, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_added',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 5, 19, 13, 6, 8, 803699, tzinfo=utc), null=True),
        ),
    ]
